version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/framework/sdk:4.8
      - image: mcr.microsoft.com/dotnet/framework/sdk:3.5

    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build $SolutionName

workflows:
  buildAll:
    jobs:
      - build
