version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor: win/server-2022
    docker:
      - image: mcr.microsoft.com/dotnet/framework/sdk:4.8
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build $SolutionName

workflows:
  version: 2.1
  buildAll:
    jobs:
      - build
